name: Writing About Menus
highlighter: pygments
markdown: kramdown
exclude: [src, bower_components, node_modules, '*.json', 'Gemfile*', 'gulpfile.js' ]
permalink: /articles/:title
s3: https://s3.amazonaws.com/curatingmenus/
